# Generated by Django 5.1.4 on 2024-12-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeClone', '0003_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
