# Generated by Django 5.1.4 on 2025-01-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_subscribers'),
        ('youtubeClone', '0005_alter_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_videos', to='channel.channel'),
        ),
    ]
